name: Deploy to GitHub pages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate static VuePress files
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - run: npm install --legacy-peer-deps
      - run: CI= npm run build

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd dist
          git init
          git add -A
          git config --local --add safe.directory /github/workspace/build
          git config --local user.email "se.ayokunle@gmail.com"
          git config --local user.name "Ayokunle Sunmola"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./dist
